apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mkonnect.fullname" . }}-config
  labels:
    {{- include "mkonnect.labels" . | nindent 4 }}
type: Opaque
stringData:
  GATEWAY_URL: {{ .Values.config.gatewayUrl | quote }}
  CONNECTOR_ID: {{ .Values.config.connectorId | quote }}
  REGISTRATION_TOKEN: ""
