apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mkonnect.fullname" . }}-config
  labels:
    {{- include "mkonnect.labels" . | nindent 4 }}
type: Opaque
data:
  GATEWAY_URL: {{ required "config.gatewayUrl is required" .Values.config.gatewayUrl | b64enc | quote }}
  CONNECTOR_ID: {{ required "config.connectorId is required" .Values.config.connectorId | b64enc | quote }}
  REGISTRATION_TOKEN: {{ .Values.config.registrationToken | default "" | b64enc | quote }}
